server:
  port: 8003
spring:
  application:
    name: service-vod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# 设置文件上传的accessKeyId和accessKeySecret
[aliyun.vod.accessKeyId]:
[aliyun.vod.accessKeySecret]: