server:
  port: 8002
spring:
  application:
    name: service-oos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

aliyun:
  oos:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      [keyid]:
      [keysecret]:
      bucketname: guli-shao-1010
